setwd("C:/Users/nopassword/Desktop")
trees<-read.csv("ta27-12.csv")
head(trees)
summary(trees)
trees<-read.csv("ta27-12.csv", na.strings='*')
summary(trees)
trees$Deer95<-factor(trees$Deer95, labels=c("None","Browsed"))
trees$Deer97<-factor(trees$Deer97, labels=c("None","Browsed"))
trees$Cover95<-factor(trees$Cover95, labels=c("None","<1/3","between 1/3 and 2/3", ">2/3"))
trees$Fert<-factor(trees$Fert, labels=c("No","Yes"))
trees$Spacing<-factor(trees$Spacing,labels=c("10feet","15 feet"))
summary(trees)
trees.fit<-lm(formula = Hgt97 ~ Hgt90 + Fert, data = trees)
summary(trees.fit)
#plot residuals versus fitted values
plot(trees.fit$fitted.values,trees.fit$residuals, ylab="Residuals",
xlab="Tree height at time of planting(cm)", main="Residual Plot for Predicting Tree Heights",pch=20)
abline(0,0)
#correlation matrix
matrix<-cor(x=trees[3:10],use="complete.obs",method="pearson")
cor(x=trees[3:10],y=trees$Hgt97, use="complete.obs",method="pearson")
trees.fit2<-lm(Hgt97~Hgt96+Hgt90+Fert,data=trees)
summary(trees.fit2)
trees.fit3<-lm(Hgt97~Diam97+Hgt96+Fert,data=trees)
summary(trees.fit3)